name: Expo CI / CD

on:
  push:
    branches: [ "master" ]
    paths:
      - '**'
      - '!**/docs/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**'
      - '!**/docs/**'

jobs:
  ci:
    name: CI (install → lint → test → build web)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache npm deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

  publish:
    name: Publish to Expo (OTA) / optional EAS build
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Setup Expo CLI + EAS
      - name: Setup Expo (CLI & EAS)
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

     
      - name: Publish OTA update (expo publish / eas update)
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: npx eas update --branch master --message "Update from CI" --non-interactive
      